// Generated by CoffeeScript 1.9.3
(function() {
    $(document).ready(function() {
        var B, T, v;
        v = new Vivus('logo', {
            type: 'delayed',
            duration: 800
        });
    });
}).call(this);
